---

name: logistic-ci

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repositry
        uses: actions/checkout@v2

      - name: Run pester tests
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Name Pester -RequiredVersion '5.2.2' -Confirm:$false -Force
          Invoke-Pester -Path ./tests/*.tests.ps1 -OutputFile ./test-results.xml -OutputFormat NUnitXml

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: ./test-results.xml
