---

name: logistic-ci

on:
  push:
    branches:
      - main

jobs:
  pester-test:
    runs-on: windows-latest

    env:
      PesterVersion: '5.2.2'

    steps:
      - name: Checkout repositry
        uses: actions/checkout@v2

      - name: Install Pester v5.2.2
        shell: pwsh
        run: |
          Write-Information -MessageData 'Installing Pester'
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Name Pester -RequiredVersion '${{ env.PesterVersion }}' -Confirm:$false -Force

      - name: Run pester tests
        shell: pwsh
        run: |
          Write-Information -MessageData 'Running Pester tests'
          Import-Module -Name Pester -RequiredVersion '${{ env.PesterVersion }}' -Force
          $PesterConfig = [PesterConfiguration]::Default
          $PesterConfig.Run.Path = './tests/*.Tests.ps1'
          $PesterConfig.TestResult.Enabled = $true
          $PesterConfig.TestResult.OutputFormat = 'JUnitXml'
          $PesterConfig.TestResult.OutputPath = './testResults.xml'
          Invoke-Pester -Configuration $PesterConfig

      # - name: Publish test results
        # uses: EnricoMi/publish-unit-test-result-action/composite@v1
        # if: always()
        # with:
          # files: ./testResults.xml

      - name: Publish test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: pester-test
          path: ./testResults.xml
