---

name: logistic-ci

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  upload-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositry
        uses: actions/checkout@v2

      - name: Upload module artifact
        uses: actions/upload-artifact@v2
        with:
          name: module
          path: src/Logistic/
